@startuml
actor "Organizer" as Organizer
actor "Admin" as Admin
actor "Guest" as Guest 
actor "Customer" as Customer


rectangle sys as "System"{
  rectangle loginSys as "LoginSystem"{
   usecase "Register" as reg
   usecase "Register User Type" as rst
   reg ..>  rst : <<includes>>

   usecase "Login" as login
   usecase "Exit" as exit

  }
   
  usecase "Purchase Tickets" as buyTickets
  usecase "View Order Summary" as orderSumm
  usecase "Check Funds" as checkFunds
  buyTickets ..> checkFunds : <<includes>>
  buyTickets ..> orderSumm : <<includes>>
  usecase "Discount" as discount
  discount ..> buyTickets : <<extends>>  

  usecase "Print Order Summary"  as POS
  Customer-->  POS
  usecase "Manage Event" as manEvent 
  usecase "Generate Event Report" as eventReport

  usecase "Manage Users" as manUser
  usecase "Manage Venue" as manVenue
  usecase "Manage Event" as manEvent

  usecase "Register Admin" as regAdmin
  manUser <.. regAdmin : <<extends>>


  Guest --> reg
  Guest --> login
  Guest --> exit 

  Customer --> buyTickets

  
  Organizer --> manEvent
  Organizer --> manVenue 
  Organizer --> eventReport
  
  Admin --> manUser
  Admin --> manEvent 
  Admin --> manVenue
  
  

}
@enduml