@startuml
left to right direction
actor "User" as user
actor "Logging CSV" as loggerCSV
actor "user CSV" as userCSV
actor "eventCSV" as eventCSV
actor "venueCSV" as venueCSV

rectangle applicationSystem as "Application System"{

  usecase "Main Menu" as mainMenu 
  usecase "Register" as register
  usecase "Login" as login 
  usecase "Exit" as exit
  
  usecase "Admin Options Menu" as adminLogin
  adminLogin --> login : <<extends>> [if user is admin]

  'Registering users' 

  usecase "Organizer Information" as organInfo
  organInfo --> register : <<extends>> [If registering as a organizer, provide organizer details] 

  usecase "User Information" as userInfo 
  userInfo --> register : <<extends>> [If user is selected, provide user details to enter]
  
  rectangle adminOptions as "Admin Options"{
    usecase "Manage Event" as manEvent
    usecase "Manage Venue" as manVenue
    usecase "Manage Users" as manUsers
    
   rectangle userOptions as "User Options"{
   usecase "Add/Update User" as addUpdateUser
   usecase "View User" as viewUser
   usecase "Delete User" as deleteUser
   usecase "Register Admin" as regAdmin
   usecase "Return to Admin Rights" as return
   
   addUpdateUser <.. regAdmin : <<extend>> [Admin can only register admin with organizer details]
   
   }

   usecase "Venue Options" as venueOptions
   usecase "Event Options" as eventOptions

   manUsers --> userOptions : <<include>>   
   manVenue --> venueOptions : <<include>>
   manEvent --> eventOptions : <<include>> 
   
   usecase logger as "Log action"

   userOptions --> logger : <<include>>
   venueOptions --> logger : <<include>>
   eventOptions --> logger : <<include>>
  
  }
}

logger --> loggerCSV
user --> register
user --> login
user --> exit

' Extend usecase relationships ' 

' Include usecase relationships ' 
  register --> userCSV : <<include>> [updating/adding user to userCSV file]
  addUpdateUser --> userCSV : <<include >> [updating/adding user to userCSV file]
  venueOptions --> venueCSV: <<include>> [updating/adding venues to venuCSV]
  eventOptions --> eventCSV: <<include>> [updating/adding events to eventCSV]
@enduml